---
abstract: 'Option and subcommand processing in the style svn(1) and git(1)'
author:
  - 'Robert Krimen, C<< <rkrimen at cpan.org> >>'
build_requires:
  Test::Most: 0
distribution_type: module
generated_by: 'Module::Install version 0.760'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Getopt-Chain
no_index:
  directory:
    - inc
    - t
requires:
  Carp::Clan::Share: 0
  Getopt::Long: 2.37
  Hash::Param: 0
  Moose: 0
  MooseX::MakeImmutable: 0.002
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/robertkrimen/getopt-chain/tree/master
version: 0.003
