---
abstract: 'svn- and git-style option and subcommand processing'
author:
  - 'Robert Krimen, C<< <rkrimen at cpan.org> >>'
build_requires:
  Test::More: 0
  Test::Most: 0
distribution_type: module
generated_by: 'Module::Install version 0.760'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Getopt-Chain
no_index:
  directory:
    - inc
    - t
requires:
  Getopt::Long: 2.37
resources:
  license: http://dev.perl.org/licenses/
version: 0.001_1
